services:
  - type: web
    name: visual-match-api
    runtime: python
    rootDir: backend
    buildCommand: |
     pip install -r backend/requirements.txt
     cd VisprodMatch
     npm install
     npm run build
    startCommand: |
     export PYTHONPATH=$PYTHONPATH:./backend
     gunicorn --chdir backend VisualDisp:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: DATABASE_URL
        value: sqlite:///DBs/products.db
      - key: PORT
        value: 4000

  - type: static
    name: visual-match-frontend
    rootDir: VisprodMatch
    buildCommand: npm install && npm run build
    publishDir: dist
    envVars:
      - key: VITE_API_URL
        fromService:
          name: visual-match-api
          type: web
          property: url